[workspace]
members = ["crates/*"]

# TODO: glob doesn't seem to work for exclude?
exclude = [
  "crates/rustc_plugin/examples/print-all-items", 
  "crates/rustc_plugin/tests/workspaces"
]

resolver = "2"