name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo-workspaces
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-workspaces
          version: 0.2.44
      - name: Run tests
        run: cargo test --all-features -- --test-threads=1
      - name: Generate documentation
        run: |
          cargo doc --all-features
          RUSTDOCFLAGS="--html-in-header scripts/katex-header.html" cargo doc --lib --no-deps --all-features
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./target/doc
          target-folder: ${{ github.ref_name }}
      - name: Publish crates
        run: cargo ws publish --from-git --yes --token ${{ secrets.CRATES_IO_TOKEN }}