name: Tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cargo clippy --all --all-features && cargo test --all --all-features -- --test-threads=1